"""Add Morador status_bot and is_sindico

Revision ID: 1adbb75a3fac
Revises: 711f4e990ac0
Create Date: 2026-06-17 21:01:57.615439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1adbb75a3fac'
down_revision: Union[str, Sequence[str], None] = '711f4e990ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import sqlmodel

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('morador', sa.Column('is_sindico', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('morador', sa.Column('status_bot', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'ATIVO'"), nullable=False))
    op.add_column('morador', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morador', 'updated_at')
    op.drop_column('morador', 'status_bot')
    op.drop_column('morador', 'is_sindico')

    # ### end Alembic commands ###
