"""Add error_message to documento

Revision ID: 356a43f1d66c
Revises: 7544ba2b0ac9
Create Date: 2026-06-18 01:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '356a43f1d66c'
down_revision: Union[str, None] = '7544ba2b0ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documento', 'error_message')
    # ### end Alembic commands ###
