"""Add ConfiguracaoIA

Revision ID: 711f4e990ac0
Revises: f9a76c92acf8
Create Date: 2026-06-17 20:55:42.533211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '711f4e990ac0'
down_revision: Union[str, Sequence[str], None] = 'f9a76c92acf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracaoia',
    sa.Column('modelo_llm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_sistema', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_criptografada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condominio_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracaoia')
    # ### end Alembic commands ###
