"""Add booking blocks fields

Revision ID: 7efa50ca3a3e
Revises: 8922c613e964
Create Date: 2026-06-19 00:08:32.923559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7efa50ca3a3e'
down_revision: Union[str, Sequence[str], None] = '8922c613e964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areacomum', sa.Column('tipo_reserva', sqlmodel.sql.sqltypes.AutoString(), server_default='DIARIA', nullable=False))
    op.add_column('areacomum', sa.Column('hora_inicio_funcionamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('areacomum', sa.Column('hora_fim_funcionamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('areacomum', sa.Column('duracao_bloco_horas', sa.Integer(), nullable=True))
    op.add_column('reserva', sa.Column('hora_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reserva', sa.Column('hora_fim', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'hora_fim')
    op.drop_column('reserva', 'hora_inicio')
    op.drop_column('areacomum', 'duracao_bloco_horas')
    op.drop_column('areacomum', 'hora_fim_funcionamento')
    op.drop_column('areacomum', 'hora_inicio_funcionamento')
    op.drop_column('areacomum', 'tipo_reserva')
    # ### end Alembic commands ###
