"""Initial migration

Revision ID: 92b95b070417
Revises: 
Create Date: 2026-05-01 21:48:42.462203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '92b95b070417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominio',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condominio_cnpj'), 'condominio', ['cnpj'], unique=True)
    op.create_index(op.f('ix_condominio_name'), 'condominio', ['name'], unique=False)
    op.create_table('areacomum',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condominio_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSANDO', 'INDEXADO', 'ERRO', name='documentostatus'), nullable=False),
    sa.Column('condominio_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morador',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('condominio_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_morador_cpf'), 'morador', ['cpf'], unique=True)
    op.create_index(op.f('ix_morador_phone'), 'morador', ['phone'], unique=True)
    op.create_table('embedding',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interacao',
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('langsmith_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('morador_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['morador_id'], ['morador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADA', 'CANCELADA', name='reservastatus'), nullable=False),
    sa.Column('morador_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areacomum.id'], ),
    sa.ForeignKeyConstraint(['morador_id'], ['morador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('interacao')
    op.drop_table('embedding')
    op.drop_index(op.f('ix_morador_phone'), table_name='morador')
    op.drop_index(op.f('ix_morador_cpf'), table_name='morador')
    op.drop_table('morador')
    op.drop_table('documento')
    op.drop_table('areacomum')
    op.drop_index(op.f('ix_condominio_name'), table_name='condominio')
    op.drop_index(op.f('ix_condominio_cnpj'), table_name='condominio')
    op.drop_table('condominio')
    # ### end Alembic commands ###
