"""Add taxa and chave_pix

Revision ID: a4591134ebdb
Revises: 850025d77789
Create Date: 2026-06-18 16:49:01.914122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a4591134ebdb'
down_revision: Union[str, Sequence[str], None] = '850025d77789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the pagamentostatus ENUM type
    op.execute("CREATE TYPE pagamentostatus AS ENUM ('ISENTO', 'PENDENTE', 'PAGO')")
    
    op.add_column('areacomum', sa.Column('taxa', sa.Float(), nullable=True))
    op.add_column('areacomum', sa.Column('chave_pix', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reserva', sa.Column('status_pagamento', sa.Enum('ISENTO', 'PENDENTE', 'PAGO', name='pagamentostatus'), nullable=False, server_default='ISENTO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'status_pagamento')
    op.drop_column('areacomum', 'chave_pix')
    op.drop_column('areacomum', 'taxa')
    op.execute("DROP TYPE pagamentostatus")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
