"""add is_escalated to interacao

Revision ID: f9a76c92acf8
Revises: 92b95b070417
Create Date: 2026-05-06 16:53:49.606265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a76c92acf8'
down_revision: Union[str, Sequence[str], None] = '92b95b070417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interacao', sa.Column('is_escalated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interacao', 'is_escalated')
    # ### end Alembic commands ###
